server.port=8081


spring.application.name=ventas-telco

# MySQL Database (persistente)
spring.datasource.url=jdbc:mysql://localhost:3306/telco_ventas?useSSL=false&serverTimezone=America/Lima&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.maximum-pool-size=10

# JPA - Hibernate MySQL
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# SQL Init
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema-mysql.sql
spring.sql.init.data-locations=classpath:data-mysql.sql

# JWT
jwt.secret=TU_CLAVE_SECRETA_MUY_LARGA_Y_SEGURA_PARA_FIRMAR_JWT_TOKENS_2024_TELCO_VENTAS_1234567890
jwt.expiration-ms=86400000

# CORS
cors.allowed-origins=http://localhost:5173
